//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

// 
// Der Quellcode wurde automatisch mit Microsoft.VSDesigner generiert. Version 4.0.30319.42000.
// 
#pragma warning disable 1591

namespace FacturaCSharpClient.FacturaTestService {
    using System;
    using System.Web.Services;
    using System.Diagnostics;
    using System.Web.Services.Protocols;
    using System.Xml.Serialization;
    using System.ComponentModel;
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Web.Services.WebServiceBindingAttribute(Name="ServerBinding", Namespace="https://test.factura.ag/soap/index")]
    public partial class ServerService : System.Web.Services.Protocols.SoapHttpClientProtocol {
        
        private System.Threading.SendOrPostCallback loginOperationCompleted;
        
        private System.Threading.SendOrPostCallback logoutOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKundeOperationCompleted;
        
        private System.Threading.SendOrPostCallback setKundeOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRechnungOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRechnungOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRechnungsturnusOperationCompleted;
        
        private System.Threading.SendOrPostCallback setRechnungsturnusOperationCompleted;
        
        private System.Threading.SendOrPostCallback getInfoboxOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechnungStornierenOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechnungMahnenOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechnungMahnverzoegerungOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechnungInkassoOperationCompleted;
        
        private System.Threading.SendOrPostCallback rechnungDirektBezahltOperationCompleted;
        
        private System.Threading.SendOrPostCallback findKundeOperationCompleted;
        
        private System.Threading.SendOrPostCallback findKundeDoubletteOperationCompleted;
        
        private System.Threading.SendOrPostCallback getKundenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRechnungenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getRechnungsturnusseOperationCompleted;
        
        private System.Threading.SendOrPostCallback verguetungsvereinbarungErzeugenOperationCompleted;
        
        private System.Threading.SendOrPostCallback forderungsverkaufOperationCompleted;
        
        private System.Threading.SendOrPostCallback bonitaetPruefenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPdfRechnungOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPdfMahnungOperationCompleted;
        
        private System.Threading.SendOrPostCallback getPdfMandatOperationCompleted;
        
        private System.Threading.SendOrPostCallback getBankdatenOperationCompleted;
        
        private System.Threading.SendOrPostCallback getIbanBicOperationCompleted;
        
        private System.Threading.SendOrPostCallback ergebnisOperationCompleted;
        
        private System.Threading.SendOrPostCallback ergebnisTextOperationCompleted;
        
        private bool useDefaultCredentialsSetExplicitly;
        
        /// <remarks/>
        public ServerService() {
            this.Url = global::FacturaCSharpClient.Properties.Settings.Default.FacturaCSharpClient_FacturaTestService_ServerService;
            if ((this.IsLocalFileSystemWebService(this.Url) == true)) {
                this.UseDefaultCredentials = true;
                this.useDefaultCredentialsSetExplicitly = false;
            }
            else {
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        public new string Url {
            get {
                return base.Url;
            }
            set {
                if ((((this.IsLocalFileSystemWebService(base.Url) == true) 
                            && (this.useDefaultCredentialsSetExplicitly == false)) 
                            && (this.IsLocalFileSystemWebService(value) == false))) {
                    base.UseDefaultCredentials = false;
                }
                base.Url = value;
            }
        }
        
        public new bool UseDefaultCredentials {
            get {
                return base.UseDefaultCredentials;
            }
            set {
                base.UseDefaultCredentials = value;
                this.useDefaultCredentialsSetExplicitly = true;
            }
        }
        
        /// <remarks/>
        public event loginCompletedEventHandler loginCompleted;
        
        /// <remarks/>
        public event logoutCompletedEventHandler logoutCompleted;
        
        /// <remarks/>
        public event getKundeCompletedEventHandler getKundeCompleted;
        
        /// <remarks/>
        public event setKundeCompletedEventHandler setKundeCompleted;
        
        /// <remarks/>
        public event getRechnungCompletedEventHandler getRechnungCompleted;
        
        /// <remarks/>
        public event setRechnungCompletedEventHandler setRechnungCompleted;
        
        /// <remarks/>
        public event getRechnungsturnusCompletedEventHandler getRechnungsturnusCompleted;
        
        /// <remarks/>
        public event setRechnungsturnusCompletedEventHandler setRechnungsturnusCompleted;
        
        /// <remarks/>
        public event getInfoboxCompletedEventHandler getInfoboxCompleted;
        
        /// <remarks/>
        public event rechnungStornierenCompletedEventHandler rechnungStornierenCompleted;
        
        /// <remarks/>
        public event rechnungMahnenCompletedEventHandler rechnungMahnenCompleted;
        
        /// <remarks/>
        public event rechnungMahnverzoegerungCompletedEventHandler rechnungMahnverzoegerungCompleted;
        
        /// <remarks/>
        public event rechnungInkassoCompletedEventHandler rechnungInkassoCompleted;
        
        /// <remarks/>
        public event rechnungDirektBezahltCompletedEventHandler rechnungDirektBezahltCompleted;
        
        /// <remarks/>
        public event findKundeCompletedEventHandler findKundeCompleted;
        
        /// <remarks/>
        public event findKundeDoubletteCompletedEventHandler findKundeDoubletteCompleted;
        
        /// <remarks/>
        public event getKundenCompletedEventHandler getKundenCompleted;
        
        /// <remarks/>
        public event getRechnungenCompletedEventHandler getRechnungenCompleted;
        
        /// <remarks/>
        public event getRechnungsturnusseCompletedEventHandler getRechnungsturnusseCompleted;
        
        /// <remarks/>
        public event verguetungsvereinbarungErzeugenCompletedEventHandler verguetungsvereinbarungErzeugenCompleted;
        
        /// <remarks/>
        public event forderungsverkaufCompletedEventHandler forderungsverkaufCompleted;
        
        /// <remarks/>
        public event bonitaetPruefenCompletedEventHandler bonitaetPruefenCompleted;
        
        /// <remarks/>
        public event getPdfRechnungCompletedEventHandler getPdfRechnungCompleted;
        
        /// <remarks/>
        public event getPdfMahnungCompletedEventHandler getPdfMahnungCompleted;
        
        /// <remarks/>
        public event getPdfMandatCompletedEventHandler getPdfMandatCompleted;
        
        /// <remarks/>
        public event getBankdatenCompletedEventHandler getBankdatenCompleted;
        
        /// <remarks/>
        public event getIbanBicCompletedEventHandler getIbanBicCompleted;
        
        /// <remarks/>
        public event ergebnisCompletedEventHandler ergebnisCompleted;
        
        /// <remarks/>
        public event ergebnisTextCompletedEventHandler ergebnisTextCompleted;
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#login", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] login(string benutzername, string passwort) {
            object[] results = this.Invoke("login", new object[] {
                        benutzername,
                        passwort});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void loginAsync(string benutzername, string passwort) {
            this.loginAsync(benutzername, passwort, null);
        }
        
        /// <remarks/>
        public void loginAsync(string benutzername, string passwort, object userState) {
            if ((this.loginOperationCompleted == null)) {
                this.loginOperationCompleted = new System.Threading.SendOrPostCallback(this.OnloginOperationCompleted);
            }
            this.InvokeAsync("login", new object[] {
                        benutzername,
                        passwort}, this.loginOperationCompleted, userState);
        }
        
        private void OnloginOperationCompleted(object arg) {
            if ((this.loginCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.loginCompleted(this, new loginCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#logout", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] logout() {
            object[] results = this.Invoke("logout", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void logoutAsync() {
            this.logoutAsync(null);
        }
        
        /// <remarks/>
        public void logoutAsync(object userState) {
            if ((this.logoutOperationCompleted == null)) {
                this.logoutOperationCompleted = new System.Threading.SendOrPostCallback(this.OnlogoutOperationCompleted);
            }
            this.InvokeAsync("logout", new object[0], this.logoutOperationCompleted, userState);
        }
        
        private void OnlogoutOperationCompleted(object arg) {
            if ((this.logoutCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.logoutCompleted(this, new logoutCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getKunde", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getKunde(int id_kunde) {
            object[] results = this.Invoke("getKunde", new object[] {
                        id_kunde});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getKundeAsync(int id_kunde) {
            this.getKundeAsync(id_kunde, null);
        }
        
        /// <remarks/>
        public void getKundeAsync(int id_kunde, object userState) {
            if ((this.getKundeOperationCompleted == null)) {
                this.getKundeOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKundeOperationCompleted);
            }
            this.InvokeAsync("getKunde", new object[] {
                        id_kunde}, this.getKundeOperationCompleted, userState);
        }
        
        private void OngetKundeOperationCompleted(object arg) {
            if ((this.getKundeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKundeCompleted(this, new getKundeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#setKunde", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] setKunde(object[] array, bool neuanlage) {
            object[] results = this.Invoke("setKunde", new object[] {
                        array,
                        neuanlage});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void setKundeAsync(object[] array, bool neuanlage) {
            this.setKundeAsync(array, neuanlage, null);
        }
        
        /// <remarks/>
        public void setKundeAsync(object[] array, bool neuanlage, object userState) {
            if ((this.setKundeOperationCompleted == null)) {
                this.setKundeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetKundeOperationCompleted);
            }
            this.InvokeAsync("setKunde", new object[] {
                        array,
                        neuanlage}, this.setKundeOperationCompleted, userState);
        }
        
        private void OnsetKundeOperationCompleted(object arg) {
            if ((this.setKundeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setKundeCompleted(this, new setKundeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getRechnung", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getRechnung(int id_rechnung) {
            object[] results = this.Invoke("getRechnung", new object[] {
                        id_rechnung});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getRechnungAsync(int id_rechnung) {
            this.getRechnungAsync(id_rechnung, null);
        }
        
        /// <remarks/>
        public void getRechnungAsync(int id_rechnung, object userState) {
            if ((this.getRechnungOperationCompleted == null)) {
                this.getRechnungOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRechnungOperationCompleted);
            }
            this.InvokeAsync("getRechnung", new object[] {
                        id_rechnung}, this.getRechnungOperationCompleted, userState);
        }
        
        private void OngetRechnungOperationCompleted(object arg) {
            if ((this.getRechnungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRechnungCompleted(this, new getRechnungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#setRechnung", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] setRechnung(object[] array) {
            object[] results = this.Invoke("setRechnung", new object[] {
                        array});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void setRechnungAsync(object[] array) {
            this.setRechnungAsync(array, null);
        }
        
        /// <remarks/>
        public void setRechnungAsync(object[] array, object userState) {
            if ((this.setRechnungOperationCompleted == null)) {
                this.setRechnungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRechnungOperationCompleted);
            }
            this.InvokeAsync("setRechnung", new object[] {
                        array}, this.setRechnungOperationCompleted, userState);
        }
        
        private void OnsetRechnungOperationCompleted(object arg) {
            if ((this.setRechnungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRechnungCompleted(this, new setRechnungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getRechnungsturnus", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getRechnungsturnus(int id_rechnungsturnus) {
            object[] results = this.Invoke("getRechnungsturnus", new object[] {
                        id_rechnungsturnus});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getRechnungsturnusAsync(int id_rechnungsturnus) {
            this.getRechnungsturnusAsync(id_rechnungsturnus, null);
        }
        
        /// <remarks/>
        public void getRechnungsturnusAsync(int id_rechnungsturnus, object userState) {
            if ((this.getRechnungsturnusOperationCompleted == null)) {
                this.getRechnungsturnusOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRechnungsturnusOperationCompleted);
            }
            this.InvokeAsync("getRechnungsturnus", new object[] {
                        id_rechnungsturnus}, this.getRechnungsturnusOperationCompleted, userState);
        }
        
        private void OngetRechnungsturnusOperationCompleted(object arg) {
            if ((this.getRechnungsturnusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRechnungsturnusCompleted(this, new getRechnungsturnusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#setRechnungsturnus", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] setRechnungsturnus(object[] array, bool neuanlage) {
            object[] results = this.Invoke("setRechnungsturnus", new object[] {
                        array,
                        neuanlage});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void setRechnungsturnusAsync(object[] array, bool neuanlage) {
            this.setRechnungsturnusAsync(array, neuanlage, null);
        }
        
        /// <remarks/>
        public void setRechnungsturnusAsync(object[] array, bool neuanlage, object userState) {
            if ((this.setRechnungsturnusOperationCompleted == null)) {
                this.setRechnungsturnusOperationCompleted = new System.Threading.SendOrPostCallback(this.OnsetRechnungsturnusOperationCompleted);
            }
            this.InvokeAsync("setRechnungsturnus", new object[] {
                        array,
                        neuanlage}, this.setRechnungsturnusOperationCompleted, userState);
        }
        
        private void OnsetRechnungsturnusOperationCompleted(object arg) {
            if ((this.setRechnungsturnusCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.setRechnungsturnusCompleted(this, new setRechnungsturnusCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getInfobox", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getInfobox() {
            object[] results = this.Invoke("getInfobox", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getInfoboxAsync() {
            this.getInfoboxAsync(null);
        }
        
        /// <remarks/>
        public void getInfoboxAsync(object userState) {
            if ((this.getInfoboxOperationCompleted == null)) {
                this.getInfoboxOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetInfoboxOperationCompleted);
            }
            this.InvokeAsync("getInfobox", new object[0], this.getInfoboxOperationCompleted, userState);
        }
        
        private void OngetInfoboxOperationCompleted(object arg) {
            if ((this.getInfoboxCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getInfoboxCompleted(this, new getInfoboxCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#rechnungStornieren", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] rechnungStornieren(int id_rechnung, bool teilstorno) {
            object[] results = this.Invoke("rechnungStornieren", new object[] {
                        id_rechnung,
                        teilstorno});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void rechnungStornierenAsync(int id_rechnung, bool teilstorno) {
            this.rechnungStornierenAsync(id_rechnung, teilstorno, null);
        }
        
        /// <remarks/>
        public void rechnungStornierenAsync(int id_rechnung, bool teilstorno, object userState) {
            if ((this.rechnungStornierenOperationCompleted == null)) {
                this.rechnungStornierenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechnungStornierenOperationCompleted);
            }
            this.InvokeAsync("rechnungStornieren", new object[] {
                        id_rechnung,
                        teilstorno}, this.rechnungStornierenOperationCompleted, userState);
        }
        
        private void OnrechnungStornierenOperationCompleted(object arg) {
            if ((this.rechnungStornierenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechnungStornierenCompleted(this, new rechnungStornierenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#rechnungMahnen", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] rechnungMahnen(int id_rechnung) {
            object[] results = this.Invoke("rechnungMahnen", new object[] {
                        id_rechnung});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void rechnungMahnenAsync(int id_rechnung) {
            this.rechnungMahnenAsync(id_rechnung, null);
        }
        
        /// <remarks/>
        public void rechnungMahnenAsync(int id_rechnung, object userState) {
            if ((this.rechnungMahnenOperationCompleted == null)) {
                this.rechnungMahnenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechnungMahnenOperationCompleted);
            }
            this.InvokeAsync("rechnungMahnen", new object[] {
                        id_rechnung}, this.rechnungMahnenOperationCompleted, userState);
        }
        
        private void OnrechnungMahnenOperationCompleted(object arg) {
            if ((this.rechnungMahnenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechnungMahnenCompleted(this, new rechnungMahnenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#rechnungMahnverzoegerung", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] rechnungMahnverzoegerung(int id_rechnung, bool weiterbelasten) {
            object[] results = this.Invoke("rechnungMahnverzoegerung", new object[] {
                        id_rechnung,
                        weiterbelasten});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void rechnungMahnverzoegerungAsync(int id_rechnung, bool weiterbelasten) {
            this.rechnungMahnverzoegerungAsync(id_rechnung, weiterbelasten, null);
        }
        
        /// <remarks/>
        public void rechnungMahnverzoegerungAsync(int id_rechnung, bool weiterbelasten, object userState) {
            if ((this.rechnungMahnverzoegerungOperationCompleted == null)) {
                this.rechnungMahnverzoegerungOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechnungMahnverzoegerungOperationCompleted);
            }
            this.InvokeAsync("rechnungMahnverzoegerung", new object[] {
                        id_rechnung,
                        weiterbelasten}, this.rechnungMahnverzoegerungOperationCompleted, userState);
        }
        
        private void OnrechnungMahnverzoegerungOperationCompleted(object arg) {
            if ((this.rechnungMahnverzoegerungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechnungMahnverzoegerungCompleted(this, new rechnungMahnverzoegerungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#rechnungInkasso", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] rechnungInkasso(int id_rechnung, int id_vertragsart, string vertragsdatum, string telefoninkasso, string ratenzahlung, string kontaktdaten) {
            object[] results = this.Invoke("rechnungInkasso", new object[] {
                        id_rechnung,
                        id_vertragsart,
                        vertragsdatum,
                        telefoninkasso,
                        ratenzahlung,
                        kontaktdaten});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void rechnungInkassoAsync(int id_rechnung, int id_vertragsart, string vertragsdatum, string telefoninkasso, string ratenzahlung, string kontaktdaten) {
            this.rechnungInkassoAsync(id_rechnung, id_vertragsart, vertragsdatum, telefoninkasso, ratenzahlung, kontaktdaten, null);
        }
        
        /// <remarks/>
        public void rechnungInkassoAsync(int id_rechnung, int id_vertragsart, string vertragsdatum, string telefoninkasso, string ratenzahlung, string kontaktdaten, object userState) {
            if ((this.rechnungInkassoOperationCompleted == null)) {
                this.rechnungInkassoOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechnungInkassoOperationCompleted);
            }
            this.InvokeAsync("rechnungInkasso", new object[] {
                        id_rechnung,
                        id_vertragsart,
                        vertragsdatum,
                        telefoninkasso,
                        ratenzahlung,
                        kontaktdaten}, this.rechnungInkassoOperationCompleted, userState);
        }
        
        private void OnrechnungInkassoOperationCompleted(object arg) {
            if ((this.rechnungInkassoCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechnungInkassoCompleted(this, new rechnungInkassoCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#rechnungDirektBezahlt", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] rechnungDirektBezahlt(int id_rechnung) {
            object[] results = this.Invoke("rechnungDirektBezahlt", new object[] {
                        id_rechnung});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void rechnungDirektBezahltAsync(int id_rechnung) {
            this.rechnungDirektBezahltAsync(id_rechnung, null);
        }
        
        /// <remarks/>
        public void rechnungDirektBezahltAsync(int id_rechnung, object userState) {
            if ((this.rechnungDirektBezahltOperationCompleted == null)) {
                this.rechnungDirektBezahltOperationCompleted = new System.Threading.SendOrPostCallback(this.OnrechnungDirektBezahltOperationCompleted);
            }
            this.InvokeAsync("rechnungDirektBezahlt", new object[] {
                        id_rechnung}, this.rechnungDirektBezahltOperationCompleted, userState);
        }
        
        private void OnrechnungDirektBezahltOperationCompleted(object arg) {
            if ((this.rechnungDirektBezahltCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.rechnungDirektBezahltCompleted(this, new rechnungDirektBezahltCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#findKunde", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] findKunde(string suchtext) {
            object[] results = this.Invoke("findKunde", new object[] {
                        suchtext});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void findKundeAsync(string suchtext) {
            this.findKundeAsync(suchtext, null);
        }
        
        /// <remarks/>
        public void findKundeAsync(string suchtext, object userState) {
            if ((this.findKundeOperationCompleted == null)) {
                this.findKundeOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindKundeOperationCompleted);
            }
            this.InvokeAsync("findKunde", new object[] {
                        suchtext}, this.findKundeOperationCompleted, userState);
        }
        
        private void OnfindKundeOperationCompleted(object arg) {
            if ((this.findKundeCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findKundeCompleted(this, new findKundeCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#findKundeDoublette", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] findKundeDoublette(string vorname, string nachname, string strasse, string hausnummer, string plz, string ort) {
            object[] results = this.Invoke("findKundeDoublette", new object[] {
                        vorname,
                        nachname,
                        strasse,
                        hausnummer,
                        plz,
                        ort});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void findKundeDoubletteAsync(string vorname, string nachname, string strasse, string hausnummer, string plz, string ort) {
            this.findKundeDoubletteAsync(vorname, nachname, strasse, hausnummer, plz, ort, null);
        }
        
        /// <remarks/>
        public void findKundeDoubletteAsync(string vorname, string nachname, string strasse, string hausnummer, string plz, string ort, object userState) {
            if ((this.findKundeDoubletteOperationCompleted == null)) {
                this.findKundeDoubletteOperationCompleted = new System.Threading.SendOrPostCallback(this.OnfindKundeDoubletteOperationCompleted);
            }
            this.InvokeAsync("findKundeDoublette", new object[] {
                        vorname,
                        nachname,
                        strasse,
                        hausnummer,
                        plz,
                        ort}, this.findKundeDoubletteOperationCompleted, userState);
        }
        
        private void OnfindKundeDoubletteOperationCompleted(object arg) {
            if ((this.findKundeDoubletteCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.findKundeDoubletteCompleted(this, new findKundeDoubletteCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getKunden", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getKunden(bool archiv) {
            object[] results = this.Invoke("getKunden", new object[] {
                        archiv});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getKundenAsync(bool archiv) {
            this.getKundenAsync(archiv, null);
        }
        
        /// <remarks/>
        public void getKundenAsync(bool archiv, object userState) {
            if ((this.getKundenOperationCompleted == null)) {
                this.getKundenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetKundenOperationCompleted);
            }
            this.InvokeAsync("getKunden", new object[] {
                        archiv}, this.getKundenOperationCompleted, userState);
        }
        
        private void OngetKundenOperationCompleted(object arg) {
            if ((this.getKundenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getKundenCompleted(this, new getKundenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getRechnungen", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getRechnungen() {
            object[] results = this.Invoke("getRechnungen", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getRechnungenAsync() {
            this.getRechnungenAsync(null);
        }
        
        /// <remarks/>
        public void getRechnungenAsync(object userState) {
            if ((this.getRechnungenOperationCompleted == null)) {
                this.getRechnungenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRechnungenOperationCompleted);
            }
            this.InvokeAsync("getRechnungen", new object[0], this.getRechnungenOperationCompleted, userState);
        }
        
        private void OngetRechnungenOperationCompleted(object arg) {
            if ((this.getRechnungenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRechnungenCompleted(this, new getRechnungenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getRechnungsturnusse", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getRechnungsturnusse() {
            object[] results = this.Invoke("getRechnungsturnusse", new object[0]);
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getRechnungsturnusseAsync() {
            this.getRechnungsturnusseAsync(null);
        }
        
        /// <remarks/>
        public void getRechnungsturnusseAsync(object userState) {
            if ((this.getRechnungsturnusseOperationCompleted == null)) {
                this.getRechnungsturnusseOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetRechnungsturnusseOperationCompleted);
            }
            this.InvokeAsync("getRechnungsturnusse", new object[0], this.getRechnungsturnusseOperationCompleted, userState);
        }
        
        private void OngetRechnungsturnusseOperationCompleted(object arg) {
            if ((this.getRechnungsturnusseCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getRechnungsturnusseCompleted(this, new getRechnungsturnusseCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#verguetungsvereinbarungErzeugen", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] verguetungsvereinbarungErzeugen(int id_kunde, int id_vertragsart, double umsatz, int raten, string faelligkeit) {
            object[] results = this.Invoke("verguetungsvereinbarungErzeugen", new object[] {
                        id_kunde,
                        id_vertragsart,
                        umsatz,
                        raten,
                        faelligkeit});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void verguetungsvereinbarungErzeugenAsync(int id_kunde, int id_vertragsart, double umsatz, int raten, string faelligkeit) {
            this.verguetungsvereinbarungErzeugenAsync(id_kunde, id_vertragsart, umsatz, raten, faelligkeit, null);
        }
        
        /// <remarks/>
        public void verguetungsvereinbarungErzeugenAsync(int id_kunde, int id_vertragsart, double umsatz, int raten, string faelligkeit, object userState) {
            if ((this.verguetungsvereinbarungErzeugenOperationCompleted == null)) {
                this.verguetungsvereinbarungErzeugenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnverguetungsvereinbarungErzeugenOperationCompleted);
            }
            this.InvokeAsync("verguetungsvereinbarungErzeugen", new object[] {
                        id_kunde,
                        id_vertragsart,
                        umsatz,
                        raten,
                        faelligkeit}, this.verguetungsvereinbarungErzeugenOperationCompleted, userState);
        }
        
        private void OnverguetungsvereinbarungErzeugenOperationCompleted(object arg) {
            if ((this.verguetungsvereinbarungErzeugenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.verguetungsvereinbarungErzeugenCompleted(this, new verguetungsvereinbarungErzeugenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#forderungsverkauf", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] forderungsverkauf(object[] array) {
            object[] results = this.Invoke("forderungsverkauf", new object[] {
                        array});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void forderungsverkaufAsync(object[] array) {
            this.forderungsverkaufAsync(array, null);
        }
        
        /// <remarks/>
        public void forderungsverkaufAsync(object[] array, object userState) {
            if ((this.forderungsverkaufOperationCompleted == null)) {
                this.forderungsverkaufOperationCompleted = new System.Threading.SendOrPostCallback(this.OnforderungsverkaufOperationCompleted);
            }
            this.InvokeAsync("forderungsverkauf", new object[] {
                        array}, this.forderungsverkaufOperationCompleted, userState);
        }
        
        private void OnforderungsverkaufOperationCompleted(object arg) {
            if ((this.forderungsverkaufCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.forderungsverkaufCompleted(this, new forderungsverkaufCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#bonitaetPruefen", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] bonitaetPruefen(int id_kunde) {
            object[] results = this.Invoke("bonitaetPruefen", new object[] {
                        id_kunde});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void bonitaetPruefenAsync(int id_kunde) {
            this.bonitaetPruefenAsync(id_kunde, null);
        }
        
        /// <remarks/>
        public void bonitaetPruefenAsync(int id_kunde, object userState) {
            if ((this.bonitaetPruefenOperationCompleted == null)) {
                this.bonitaetPruefenOperationCompleted = new System.Threading.SendOrPostCallback(this.OnbonitaetPruefenOperationCompleted);
            }
            this.InvokeAsync("bonitaetPruefen", new object[] {
                        id_kunde}, this.bonitaetPruefenOperationCompleted, userState);
        }
        
        private void OnbonitaetPruefenOperationCompleted(object arg) {
            if ((this.bonitaetPruefenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.bonitaetPruefenCompleted(this, new bonitaetPruefenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getPdfRechnung", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getPdfRechnung(int id_rechnung) {
            object[] results = this.Invoke("getPdfRechnung", new object[] {
                        id_rechnung});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getPdfRechnungAsync(int id_rechnung) {
            this.getPdfRechnungAsync(id_rechnung, null);
        }
        
        /// <remarks/>
        public void getPdfRechnungAsync(int id_rechnung, object userState) {
            if ((this.getPdfRechnungOperationCompleted == null)) {
                this.getPdfRechnungOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPdfRechnungOperationCompleted);
            }
            this.InvokeAsync("getPdfRechnung", new object[] {
                        id_rechnung}, this.getPdfRechnungOperationCompleted, userState);
        }
        
        private void OngetPdfRechnungOperationCompleted(object arg) {
            if ((this.getPdfRechnungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPdfRechnungCompleted(this, new getPdfRechnungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getPdfMahnung", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getPdfMahnung(int id_mahnung) {
            object[] results = this.Invoke("getPdfMahnung", new object[] {
                        id_mahnung});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getPdfMahnungAsync(int id_mahnung) {
            this.getPdfMahnungAsync(id_mahnung, null);
        }
        
        /// <remarks/>
        public void getPdfMahnungAsync(int id_mahnung, object userState) {
            if ((this.getPdfMahnungOperationCompleted == null)) {
                this.getPdfMahnungOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPdfMahnungOperationCompleted);
            }
            this.InvokeAsync("getPdfMahnung", new object[] {
                        id_mahnung}, this.getPdfMahnungOperationCompleted, userState);
        }
        
        private void OngetPdfMahnungOperationCompleted(object arg) {
            if ((this.getPdfMahnungCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPdfMahnungCompleted(this, new getPdfMahnungCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getPdfMandat", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getPdfMandat(string mandat_referenznummer) {
            object[] results = this.Invoke("getPdfMandat", new object[] {
                        mandat_referenznummer});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getPdfMandatAsync(string mandat_referenznummer) {
            this.getPdfMandatAsync(mandat_referenznummer, null);
        }
        
        /// <remarks/>
        public void getPdfMandatAsync(string mandat_referenznummer, object userState) {
            if ((this.getPdfMandatOperationCompleted == null)) {
                this.getPdfMandatOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetPdfMandatOperationCompleted);
            }
            this.InvokeAsync("getPdfMandat", new object[] {
                        mandat_referenznummer}, this.getPdfMandatOperationCompleted, userState);
        }
        
        private void OngetPdfMandatOperationCompleted(object arg) {
            if ((this.getPdfMandatCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getPdfMandatCompleted(this, new getPdfMandatCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getBankdaten", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getBankdaten(string blzOderBic) {
            object[] results = this.Invoke("getBankdaten", new object[] {
                        blzOderBic});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getBankdatenAsync(string blzOderBic) {
            this.getBankdatenAsync(blzOderBic, null);
        }
        
        /// <remarks/>
        public void getBankdatenAsync(string blzOderBic, object userState) {
            if ((this.getBankdatenOperationCompleted == null)) {
                this.getBankdatenOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetBankdatenOperationCompleted);
            }
            this.InvokeAsync("getBankdaten", new object[] {
                        blzOderBic}, this.getBankdatenOperationCompleted, userState);
        }
        
        private void OngetBankdatenOperationCompleted(object arg) {
            if ((this.getBankdatenCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getBankdatenCompleted(this, new getBankdatenCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#getIbanBic", RequestNamespace="https://test.factura.ag/soap/index", ResponseNamespace="https://test.factura.ag/soap/index")]
        [return: System.Xml.Serialization.SoapElementAttribute("return")]
        public object[] getIbanBic(int blz, int kontonummer) {
            object[] results = this.Invoke("getIbanBic", new object[] {
                        blz,
                        kontonummer});
            return ((object[])(results[0]));
        }
        
        /// <remarks/>
        public void getIbanBicAsync(int blz, int kontonummer) {
            this.getIbanBicAsync(blz, kontonummer, null);
        }
        
        /// <remarks/>
        public void getIbanBicAsync(int blz, int kontonummer, object userState) {
            if ((this.getIbanBicOperationCompleted == null)) {
                this.getIbanBicOperationCompleted = new System.Threading.SendOrPostCallback(this.OngetIbanBicOperationCompleted);
            }
            this.InvokeAsync("getIbanBic", new object[] {
                        blz,
                        kontonummer}, this.getIbanBicOperationCompleted, userState);
        }
        
        private void OngetIbanBicOperationCompleted(object arg) {
            if ((this.getIbanBicCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.getIbanBicCompleted(this, new getIbanBicCompletedEventArgs(invokeArgs.Results, invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#ergebnis", RequestNamespace="https://test.factura.ag/soap/index", OneWay=true)]
        public void ergebnis(object ergebnisSchluessel, object durchschlag, object textZusatz, object fehler) {
            this.Invoke("ergebnis", new object[] {
                        ergebnisSchluessel,
                        durchschlag,
                        textZusatz,
                        fehler});
        }
        
        /// <remarks/>
        public void ergebnisAsync(object ergebnisSchluessel, object durchschlag, object textZusatz, object fehler) {
            this.ergebnisAsync(ergebnisSchluessel, durchschlag, textZusatz, fehler, null);
        }
        
        /// <remarks/>
        public void ergebnisAsync(object ergebnisSchluessel, object durchschlag, object textZusatz, object fehler, object userState) {
            if ((this.ergebnisOperationCompleted == null)) {
                this.ergebnisOperationCompleted = new System.Threading.SendOrPostCallback(this.OnergebnisOperationCompleted);
            }
            this.InvokeAsync("ergebnis", new object[] {
                        ergebnisSchluessel,
                        durchschlag,
                        textZusatz,
                        fehler}, this.ergebnisOperationCompleted, userState);
        }
        
        private void OnergebnisOperationCompleted(object arg) {
            if ((this.ergebnisCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ergebnisCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        [System.Web.Services.Protocols.SoapRpcMethodAttribute("https://test.factura.ag/soap/index#ergebnisText", RequestNamespace="https://test.factura.ag/soap/index", OneWay=true)]
        public void ergebnisText(object loginErgebnisSchluessel) {
            this.Invoke("ergebnisText", new object[] {
                        loginErgebnisSchluessel});
        }
        
        /// <remarks/>
        public void ergebnisTextAsync(object loginErgebnisSchluessel) {
            this.ergebnisTextAsync(loginErgebnisSchluessel, null);
        }
        
        /// <remarks/>
        public void ergebnisTextAsync(object loginErgebnisSchluessel, object userState) {
            if ((this.ergebnisTextOperationCompleted == null)) {
                this.ergebnisTextOperationCompleted = new System.Threading.SendOrPostCallback(this.OnergebnisTextOperationCompleted);
            }
            this.InvokeAsync("ergebnisText", new object[] {
                        loginErgebnisSchluessel}, this.ergebnisTextOperationCompleted, userState);
        }
        
        private void OnergebnisTextOperationCompleted(object arg) {
            if ((this.ergebnisTextCompleted != null)) {
                System.Web.Services.Protocols.InvokeCompletedEventArgs invokeArgs = ((System.Web.Services.Protocols.InvokeCompletedEventArgs)(arg));
                this.ergebnisTextCompleted(this, new System.ComponentModel.AsyncCompletedEventArgs(invokeArgs.Error, invokeArgs.Cancelled, invokeArgs.UserState));
            }
        }
        
        /// <remarks/>
        public new void CancelAsync(object userState) {
            base.CancelAsync(userState);
        }
        
        private bool IsLocalFileSystemWebService(string url) {
            if (((url == null) 
                        || (url == string.Empty))) {
                return false;
            }
            System.Uri wsUri = new System.Uri(url);
            if (((wsUri.Port >= 1024) 
                        && (string.Compare(wsUri.Host, "localHost", System.StringComparison.OrdinalIgnoreCase) == 0))) {
                return true;
            }
            return false;
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void loginCompletedEventHandler(object sender, loginCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class loginCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal loginCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void logoutCompletedEventHandler(object sender, logoutCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class logoutCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal logoutCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getKundeCompletedEventHandler(object sender, getKundeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKundeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKundeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setKundeCompletedEventHandler(object sender, setKundeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setKundeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setKundeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRechnungCompletedEventHandler(object sender, getRechnungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRechnungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRechnungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setRechnungCompletedEventHandler(object sender, setRechnungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRechnungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRechnungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRechnungsturnusCompletedEventHandler(object sender, getRechnungsturnusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRechnungsturnusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRechnungsturnusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void setRechnungsturnusCompletedEventHandler(object sender, setRechnungsturnusCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class setRechnungsturnusCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal setRechnungsturnusCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getInfoboxCompletedEventHandler(object sender, getInfoboxCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getInfoboxCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getInfoboxCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void rechnungStornierenCompletedEventHandler(object sender, rechnungStornierenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechnungStornierenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechnungStornierenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void rechnungMahnenCompletedEventHandler(object sender, rechnungMahnenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechnungMahnenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechnungMahnenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void rechnungMahnverzoegerungCompletedEventHandler(object sender, rechnungMahnverzoegerungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechnungMahnverzoegerungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechnungMahnverzoegerungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void rechnungInkassoCompletedEventHandler(object sender, rechnungInkassoCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechnungInkassoCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechnungInkassoCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void rechnungDirektBezahltCompletedEventHandler(object sender, rechnungDirektBezahltCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class rechnungDirektBezahltCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal rechnungDirektBezahltCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void findKundeCompletedEventHandler(object sender, findKundeCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findKundeCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findKundeCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void findKundeDoubletteCompletedEventHandler(object sender, findKundeDoubletteCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class findKundeDoubletteCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal findKundeDoubletteCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getKundenCompletedEventHandler(object sender, getKundenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getKundenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getKundenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRechnungenCompletedEventHandler(object sender, getRechnungenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRechnungenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRechnungenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getRechnungsturnusseCompletedEventHandler(object sender, getRechnungsturnusseCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getRechnungsturnusseCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getRechnungsturnusseCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void verguetungsvereinbarungErzeugenCompletedEventHandler(object sender, verguetungsvereinbarungErzeugenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class verguetungsvereinbarungErzeugenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal verguetungsvereinbarungErzeugenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void forderungsverkaufCompletedEventHandler(object sender, forderungsverkaufCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class forderungsverkaufCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal forderungsverkaufCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void bonitaetPruefenCompletedEventHandler(object sender, bonitaetPruefenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class bonitaetPruefenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal bonitaetPruefenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPdfRechnungCompletedEventHandler(object sender, getPdfRechnungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPdfRechnungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPdfRechnungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPdfMahnungCompletedEventHandler(object sender, getPdfMahnungCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPdfMahnungCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPdfMahnungCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getPdfMandatCompletedEventHandler(object sender, getPdfMandatCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getPdfMandatCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getPdfMandatCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getBankdatenCompletedEventHandler(object sender, getBankdatenCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getBankdatenCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getBankdatenCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void getIbanBicCompletedEventHandler(object sender, getIbanBicCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    public partial class getIbanBicCompletedEventArgs : System.ComponentModel.AsyncCompletedEventArgs {
        
        private object[] results;
        
        internal getIbanBicCompletedEventArgs(object[] results, System.Exception exception, bool cancelled, object userState) : 
                base(exception, cancelled, userState) {
            this.results = results;
        }
        
        /// <remarks/>
        public object[] Result {
            get {
                this.RaiseExceptionIfNecessary();
                return ((object[])(this.results[0]));
            }
        }
    }
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ergebnisCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Web.Services", "4.8.3752.0")]
    public delegate void ergebnisTextCompletedEventHandler(object sender, System.ComponentModel.AsyncCompletedEventArgs e);
}

#pragma warning restore 1591